### ISSUE TITLE
Violation of license of scriban

### ISSUE THREAD

**Issue by xoofx** [lizoc/textscript#3]
Hi,
You are currently using the entire codebase of the scriban project https://github.com/lunet-io/scriban without retaining the original license which is violating its usage. 

So please, I'm asking you to fix your license.

For guidance for your users, I would also appreciate that you specify that you are actually forking the original project scriban. Using a project like this (including the documentation) without properly giving back credits is really not the way to play respectfully in OSS world.

**Comment by xoofx** [comment]
Nevermind, I found the license in https://github.com/lizoc/textscript/blob/master/THIRD-PARTY-LICENSE.txt

**Comment by xoofx** [comment]
Reopening because you have been removing the license headers in the source files, while they should not be removed:

```
// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license. 
// See license.txt file in the project root for full license information.
```

Please update your code base to reflect that this header should not be removed.

**Comment by imacks** [comment]
Hi there. Sorry if you feel violated, that was certainly not the intention. I've added your copyright header to all files that contained your code. Let me know if you are satisfied.

If you would like more credit exposure beyond that and the third party license doc, I can also add something at the top of the readme, along the lines of "this project is adopted from scriban etc..". If you have wording in mind just let me know too.

FYI, numerous breaking changes are made and will be made here for my specific needs, things you probably would not care to consider in your project. That's why this is a hard fork that's expected to diverge from your code base in time. However, I have a fork on your repo too, and I do hope you are still cool if I make any PRs to your scriban project in the future based on that?

**Comment by xoofx** [comment]
> If you would like more credit exposure beyond that and the third party license doc, I can also add something at the top of the readme, along the lines of "this project is adopted from scriban etc..". If you have wording in mind just let me know too.

I  would prefer that instead of listing scriban as part of the _"We take inspirations from the following repos"_  you should separate it from the rest of this list (frankly, this is not just "inspiration" in the case of scriban) and explicit that TextScript is a fork of scriban, and explaining why. It will provide better guidance and avoid confusion.

**Comment by imacks** [comment]
As I said

> I can also add something at the top of the readme, along the lines
> of "this project is adopted from scriban etc.."

I have decided to add a big banner at the top of the readme that says this is a fork from your repo. I'll let you know once that's done, probably after new year.

**Comment by imacks** [comment]
Honestly, it was a oversight on my part to remove the header copyright notice, but that has since been fixed in the previous commit. I hope that means it's all good legally.

Coupled with the fork clarification I just said, I trust you have nothing to add?

**Comment by xoofx** [comment]
> Coupled with the fork clarification I just said, I trust you have nothing to add?

No that should be fine, thanks.

**Comment by imacks** [comment]
closing for now. feel free to open again if you are still having issues.
